In [3]:
import pandas as pd

df = pd.read_csv("/Users/bumky/Documents/vgames2.csv")
df.head()

,Unnamed: 0,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
0,1,Candace Kane's Candy Factory,DS,2008.0,Action,Destineer,0.04,0,0,0
1,2,The Munchables,Wii,2009.0,Action,Namco Bandai Games,0.17,0,0,0.01
2,3,Otome wa Oanesama Boku ni Koi Shiteru Portable,PSP,2010.0,Adventure,Alchemist,0,0,0.02,0
3,4,Deal or No Deal: Special Edition,DS,2010.0,Misc,Zoo Games,0.04,0,0,0
4,5,Ben 10 Ultimate Alien: Cosmic Destruction,PS3,2010.0,Platform,D3Publisher,0.12,0.09,0,0.04

In [4]:
import os
print(os.getcwd())
df.info

/Users/bumky/Untitled Folder

<bound method DataFrame.info of        Unnamed: 0                                            Name Platform  \
0               1                    Candace Kane's Candy Factory       DS
1               2                                  The Munchables      Wii
2               3  Otome wa Oanesama Boku ni Koi Shiteru Portable      PSP
3               4                Deal or No Deal: Special Edition       DS
4               5       Ben 10 Ultimate Alien: Cosmic Destruction      PS3
...           ...                                             ...      ...
16593       16594                         Ice Age 2: The Meltdown       GC
16594       16595                     Rainbow Islands: Revolution      PSP
16595       16596                                        NBA 2K16      PS3
16596       16597                     Toukiden: The Age of Demons      PSV
16597       16598                        The King of Fighters '95       PS

         Year      Genre                    Publisher NA_Sales EU_Sales  \
0      2008.0     Action                    Destineer     0.04        0
1      2009.0     Action           Namco Bandai Games     0.17        0
2      2010.0  Adventure                    Alchemist        0        0
3      2010.0       Misc                    Zoo Games     0.04        0
4      2010.0   Platform                  D3Publisher     0.12     0.09
...       ...        ...                          ...      ...      ...
16593  2006.0   Platform                Vivendi Games     0.15     0.04
16594  2005.0     Action            Rising Star Games     0.01        0
16595  2015.0     Sports         Take-Two Interactive     0.44     0.19
16596  2013.0     Action                   Tecmo Koei     0.05     0.05
16597  1996.0   Fighting  Sony Computer Entertainment        0        0

      JP_Sales Other_Sales
0            0           0
1            0        0.01
2         0.02           0
3            0           0
4            0        0.04
...        ...         ...
16593        0        0.01
16594        0           0
16595     0.03        0.13
16596     0.25        0.03
16597     0.16        0.01

[16598 rows x 10 columns]>

In [1]:
### EDA

# 결측치 제거: 결측치 N/A이 포함된 행 삭제
# 출고량 단위 변경: K 단위를 *1000, M 단위를 *1000000으로 변경

In [7]:
df.dropna()

,Unnamed: 0,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
0,1,Candace Kane's Candy Factory,DS,2008.0,Action,Destineer,0.04,0,0,0
1,2,The Munchables,Wii,2009.0,Action,Namco Bandai Games,0.17,0,0,0.01
2,3,Otome wa Oanesama Boku ni Koi Shiteru Portable,PSP,2010.0,Adventure,Alchemist,0,0,0.02,0
3,4,Deal or No Deal: Special Edition,DS,2010.0,Misc,Zoo Games,0.04,0,0,0
4,5,Ben 10 Ultimate Alien: Cosmic Destruction,PS3,2010.0,Platform,D3Publisher,0.12,0.09,0,0.04
...,...,...,...,...,...,...,...,...,...,...
16593,16594,Ice Age 2: The Meltdown,GC,2006.0,Platform,Vivendi Games,0.15,0.04,0,0.01
16594,16595,Rainbow Islands: Revolution,PSP,2005.0,Action,Rising Star Games,0.01,0,0,0
16595,16596,NBA 2K16,PS3,2015.0,Sports,Take-Two Interactive,0.44,0.19,0.03,0.13
16596,16597,Toukiden: The Age of Demons,PSV,2013.0,Action,Tecmo Koei,0.05,0.05,0.25,0.03
16597,16598,The King of Fighters '95,PS,1996.0,Fighting,Sony Computer Entertainment,0,0,0.16,0.01

In [20]:
def unit_k(string):
    return float(string.replace('K', '000'))
        
#def unit_M(string):
 #   return float(string.replace('M', '000000'))

In [21]:
df['NA_Sales'] = df['NA_Sales'].apply(unit_k)
df['EU_sales'] = df['NA_Sales'].apply(unit_k)
df['JP_sales'] = df['JP_Sales'].apply(unit_k)
df['Other_sales'] = df['Other_Sales'].apply(unit_k)
df

ValueError: could not convert string to float: '0.58M'

In [19]:
### 1. 지역에 따라 선호하는 게임 장르가 다를까

# 가설: 지역에 따라 선호하는 게임 장르가 같다.

# ANOVA test를 통해 4개의 지역 그룹에서 차이가 있는지를 가설 검정

# 변수(지역), 장르

from scipy import stats

In [ ]:
### 2. 연도별 게임의 트렌드가 있을까

# 가설: 연도별 게임의 트렌드가 존재하지 않는다.

# 범주형 데이터인 연도(year)과 트렌드(지역 별 출고량의 합)을 비교하여 가설 검정

In [ ]:
### 3. 출고량이 높은 게임에 대한 분석 및 시각화 프로세스